# Generated by Django 4.2.4 on 2024-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='coding.jpeg', upload_to='profile_pics'),
        ),
    ]
