# Generated by Django 5.0.7 on 2024-07-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
